### ISSUE TITLE
About GTA dataset

### ISSUE THREAD

**Issue by O-VIGIA** [leolyj/DCA-SRSFE#3]
Hi, your download link is invalid, may you update it, please?  Thanks so much!

**Comment by O-VIGIA** [comment]
> Hi, your download link is invalid, may you update it, please? Thanks so much!

Thanks for your update!

**Comment by curiosity654** [comment]
Hi, did you download the data correctly? I cannot open the onedrive link.

**Comment by O-VIGIA** [comment]
Yes, i did it&nbsp; two months ago, but sometimes its download link will be closed ,and I dontknow why.



---Original---
From: ***@***.***&gt;
Date: Thu, Dec 22, 2022 09:25 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [leolyj/DCA-SRSFE] About GTA dataset (Issue #3)




 
Hi, did you download the data correctly? I cannot open the onedrive link.
