### ISSUE TITLE
question about lyft dataset

### ISSUE THREAD

**Issue by summerice9** [leolyj/DCA-SRSFE#4]
Thanks for sharing the code. 

I have a question about the code of lyft_precessing.py. This code takes "train.txt", "val.txt", and 'test.txt' as input. However,  these txt files are not provided. Could you please share these files?

**Comment by JZ-9962** [comment]
Hi,  we have added them to ./data/Lyft/ImageSets and updated instructions for Lyft dataset. Good luck!
